package br.com.lucianoluzzi.currencyrateconverter.repository.dto

import java.math.BigDecimal

class RatesDTO {
    var aud = BigDecimal(0.0)
    var bgn = BigDecimal(0.0)
    var brl = BigDecimal(0.0)
    var cad = BigDecimal(0.0)
    var chf = BigDecimal(0.0)
    var cny = BigDecimal(0.0)
    var czk = BigDecimal(0.0)
    var dkk = BigDecimal(0.0)
    var gbp = BigDecimal(0.0)
    var hkd = BigDecimal(0.0)
    var hrk = BigDecimal(0.0)
    var huf = BigDecimal(0.0)
    var idr = BigDecimal(0.0)
    var ils = BigDecimal(0.0)
    var inr = BigDecimal(0.0)
    var isk = BigDecimal(0.0)
    var jpy = BigDecimal(0.0)
    var krw = BigDecimal(0.0)
    var mxn = BigDecimal(0.0)
    var myr = BigDecimal(0.0)
    var nok = BigDecimal(0.0)
    var nzd = BigDecimal(0.0)
    var php = BigDecimal(0.0)
    var pln = BigDecimal(0.0)
    var ron = BigDecimal(0.0)
    var rub = BigDecimal(0.0)
    var sek = BigDecimal(0.0)
    var sgd = BigDecimal(0.0)
    var thb = BigDecimal(0.0)
    var `try` = BigDecimal(0.0)
    var usd = BigDecimal(0.0)
    var zar = BigDecimal(0.0)
}